In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr , type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [11]:
import numpy as np
import time

In [12]:
#execution performation
size = 10_000_000

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} second")

#numoy list array
np_arr = np.array(py_list)
start =time.time()
sq_array = np_arr **2
end = time.time()
print(f"numpy list time = {end-start} second")


python list time = 1.1368515491485596 second
numpy list time = 0.027806758880615234 second


In [14]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} , bytes")
print(f"numpy array size = {np_arr.nbytes} , bytes")


python list size = 800000560000000 , bytes
numpy array size = 80000000 , bytes


In [2]:
import numpy as np



In [3]:
#create - from lists
arr = np.array([1,2,3,4,5,6])
print(arr , type(arr))
arr2  = np.array([4,5,6,"prime"])
print(arr2 , type(arr2) , arr2.dtype , arr2.shape)
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d , arr2d.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'>
['4' '5' '6' 'prime'] <class 'numpy.ndarray'> <U21 (4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [14]:
arr1 = np.zeros((3,3) , dtype = "int64")
print(arr1 , arr1.shape )

arr2 = np.ones((3,3) , dtype = "int64")
print(arr2, arr2.shape )

arr3 = np.full((3,4) , 100)
print(arr3 , arr3.shape)


[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [25]:
arr4 = np.eye(4)
print(arr4 , arr4.shape )


arr5 = np.arange(1,11)
print(arr5, arr5.shape )

arr6 = np.linspace(1,100 , 3)
print(arr6, arr6.shape )

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.   50.5 100. ] (3,)


In [27]:
import numpy as np
arr =  np.array([[1,2,3] ,[4,5,6] ,[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [36]:
arr =  np.array([[1,2,3] ,[4,5,6]])
reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)

flattend = arr.flatten()
print(flattend , flattend.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [37]:
arr = np.array([1,2,4,3,5,6])
print(arr[2])

4


In [38]:
arr =  np.array([[1,2,3] ,[4,5,6]])
print(arr[1][2])

6


In [40]:
arr = np.array([1,2,4,3,5,6])#fancy idx
idx = [0,4,5]
print(arr[idx])

[1 5 6]


In [42]:
#boolean idx
arr = np.array([1,2,4,3,5,6])
print(arr[arr>4])
print(arr[arr%2 ==0])

[5 6]
[2 4 6]


In [ ]:
#slicing
arr = np.array([1,2,4,3,5,6])
print(arr[1:4])